//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mv_impinj.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mv_impinj.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block;vertical-ali [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_min {
            get {
                return ResourceManager.GetString("bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;HEAD&gt;
        ///    &lt;Title&gt;Impinj MobileView Connector Configuration&lt;/Title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/bootstrap.min.css&quot; /&gt;
        ///&lt;/HEAD&gt;
        ///&lt;Body&gt;
        ///&lt;nav class=&quot;navbar navbar-default&quot;&gt;
        ///    &lt;div class=&quot;container-fluid&quot;&gt;
        ///        &lt;div class=&quot;navbar-header&quot;&gt;
        ///            &lt;a class=&quot;navbar-brand&quot; href=&quot;http://www.impinj.com&quot; style=&quot;padding:0;&quot;&gt;
        ///                &lt;img alt=&quot;Brand&quot; src=&quot;/logo.png&quot; style=&quot;width: 100px;&quot;&gt;
        ///            &lt;/a&gt;
        ///        &lt;/div&gt;
        ///        &lt;h2 style=&quot;text-align: center; padding-le [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&apos;alert {2} text-center&apos;&gt; {0} &lt;form method=&apos;POST&apos; action=&apos;/service/run&apos;&gt;{1}&lt;/form&gt;&lt;/div&gt;.
        /// </summary>
        internal static string FlashMsgTemplate {
            get {
                return ResourceManager.GetString("FlashMsgTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&apos;submit&apos; value=&apos;Run Service&apos; class=&apos;btn btn-primary&apos;&gt;.
        /// </summary>
        internal static string RunButton {
            get {
                return ResourceManager.GetString("RunButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;HEAD&gt;
        ///    &lt;Title&gt;Impinj MobileView Connector Status&lt;/Title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/bootstrap.min.css&quot; /&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///        function replaceData(obj) {
        ///            var el;
        ///            for(var i in obj)
        ///                if (obj.hasOwnProperty(i))
        ///                    if((el = document.getElementById(i)))
        ///                        el.innerHTML = obj[i];
        ///        }
        ///        function refreshData() {
        ///            var xmlHttp = new XMLHttpRequest();
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
    }
}
